package divyansh.tech.bhagwad_geeta.models.gson.shlokas


import com.google.gson.annotations.SerializedName

data class Raman(
    @SerializedName("author")
    val author: String, // Sri Ramanuja
    @SerializedName("et")
    val et: String, // 1.1 - 1.19 Dhrtarastra said - Sanjaya said  Duryodhana, after viewing the forces of Pandavas protected by Bhima, and his own forces protected by Bhisma conveyed his views thus to Drona, his teacher, about the adeacy of Bhima's forces for conering the Kaurava forces and the inadeacy of his own forces for victory against the Pandava forces. He was grief-stricken within.Observing his (Duryodhana's) despondecny, Bhisma, in order to cheer him, roared like a lion, and then blowing his conch, made his side sound their conchs and kettle-drums, which made an uproar as a sign of victory. Then, having heard that great tumult, Arjuna and Sri Krsna the Lord of all lords, who was acting as the charioteer of Arjuna, sitting in their great chariot which was powerful enough to coner the three worlds; blew their divine conchs Srimad Pancajanya and Devadatta. Then, both Yudhisthira and Bhima blew their respective conchs separately. That tumult rent asunder the hearts of your sons, led by Duryodhana. The sons of Dhrtarastra then thought, 'Our cause is almost lost now itself.' So said Sanjaya to Dhrtarastra who was longing for their victory.Sanjaya said to Dhrtarastra:  Then, seeing the Kauravas, who were ready for battle, Arjuna, who had Hanuman, noted for his exploit of burning Lanka, as the emblem on his flag on his chariot, directed his charioteer Sri Krsna, the Supreme Lord-who is overcome by parental love for those who take shelter in Him who is the treasure-house of knowledge, power, lordship, energy, potency and splendour, whose sportive delight brings about the origin, sustentation and dissolution of the entire cosmos at His will, who is the Lord of the senses, who controls in all ways the senses inner and outer of all, superior and inferior - by saying, 'Station my chariot in an appropriate place in order that I may see exactly my enemies who are eager for battle.'
    @SerializedName("sc")
    val sc: String // ।।1.2।।धृतराष्ट्र उवाच  सञ्जय उवाच  दुर्योधनः स्वयमेव भीमाभिरक्षितं पाण्डवानां बलम् आत्मीयं च भीष्माभिरक्षितं बलम् अवलोक्य आत्मविजये तस्य बलस्य पर्याप्तताम् आत्मीयस्य बलस्य तद्विजये चापर्याप्तताम् आचार्याय निवेद्य अन्तरे विषण्णः अभवत्। तस्य विषादम् आलोक्य भीष्मः तस्य हर्षं जनयितुं सिंहनादं शङ्खाध्मानं च कृत्वा शङ्खभेरीनिनादैः च विजयाभिशंसिनं घोषं च अकारयत्। ततः तं घोषम् आकर्ण्य सर्वेश्वरेश्वरः पार्थसारथी रथी च पाण्डुतनयः त्रैलोक्यविजयोपकरणभूते महति स्यन्दने स्थितौ त्रैलोक्यं कम्पयन्तौ श्रीमत्पाञ्चजन्यदेवदत्तौ दिव्यौ शङ्खौ प्रदध्मतुः। ततो युधिष्ठिरवृकोदरादयः च स्वकीयान् शङ्खान् पृथक् पृथक् प्रदध्मुः। स घोषो दुर्योधनप्रमुखानां सर्वेषाम् एव भवत्पुत्राणां हृदयानि बिभेद। अद्य एव नष्टं कुरूणां बलम् इति धार्त्तराष्ट्रा मेनिरे। एवं तद्विजयाभिकाङ्क्षिणे धृतराष्ट्राय संजयः अकथयत्।अथ युयुत्सून् अवस्थितान् धार्तराष्ट्रान् भीष्मद्रोणप्रमुखान् दृष्ट्वा लङ्कादहनवानरध्वजः पाण्डुतनयो ज्ञानशक्तिबलैश्वर्यवीर्यतेजसां निधिं स्वसंकल्पकृतजगदुदयविभवलयलीलं हृषीकेशं परावरनिखिलजनान्तर्बाह्यसर्वकरणानां सर्वप्रकारकनियमने अवस्थितं समाश्रितवात्सल्यविवशतया स्वसारथ्ये अवस्थितं युयुत्सून् यथावत् अवेक्षितुं तदीक्षणक्षमे स्थाने रथं स्थापय इति अचोदयत्।
)